Rise-Vision/widget-tester

- index.js
It will redirect to index.html it is on.
@olegrise could you please review. This is a modrewrite which the servers needs to implement when html5 push state mode is on on the app. I added it here so local dev server for store can work properly.
cheers
> Added a option for html5 push state mode

- mocks/rise-storage-mock.js
Reverts Rise-Vision/widget-tester#59
> Revert "Add cache buster to URL"

- index.js
so it can be used for login on e2e testing
@alex-deaconu please review. cheers
> Added user and password parameters

- package.json
@alex-deaconu I upgraded protractor to try to fix the issue we have with selenium on the scenario-runner . Could you please review? cheers
> Upgraded gulp-protractor to the latest version.

- package.json
Reverts Rise-Vision/widget-tester#63
@alex-deaconu FYI.
> Revert "Upgraded gulp-protractor to the latest version."

- package.json
Reverts Rise-Vision/widget-tester#65
> Revert "fix sinon version"

- mocks/segment-analytics-mock.js
Common mock that disables segment script loading. Fixes broken unit tests and disables segment tracking for unit tests.
@olegrise @rodrigopavezi please review. Thanks!
> [feature] Segment mock that disables tracking script

- mocks/segment-analytics-mock.js
Missed updating the module name here, it's causing tests to fail.
@rodrigopavezi please review. Thanks!
> Updating segmentAnalytics module name

- mocks/gadget-mocks.js
Return a default value for `rsH` in `getInt` function.
> Implement getInt

- index.js
- package.json
- protractor.conf.js
spec-xunit-file and mocha-proshot
so we have xunit reporting together
specs and screenshots.
@alex-deaconu @ezequielc please review. cheers
> Changed protractor report to use

- index.js
- package.json
- protractor.conf.js
Reverts Rise-Vision/widget-tester#73
@alex-deaconu reverting this as it is breaking the builds.  Cheers
> Revert "Changed protractor report to use"

- index.js
Second user needed for registration scenarios in CH.
@rodrigopavezi please review. Thanks.
> Add second set of login credentials

- mocks/translate-mock.js
@ezequielc please review. cheers
> added translate mock for angular-translate

- index.js
- package.json
- Code coverage for unit tests
- Support for coveralls.io
@rodrigopavezi Please review. Thanks
> code coverage support

- bower.json
- package.json
@rodrigopavezi please review. Cheers
> Updating package version

- bower.json
- mocks/logger-mock.js
- package.json
- Maintaining necessary functionality where necessary, ensuring no functionality for actual post requests to BQ
> Adding widget logger mock

- bower.json
- mocks/logger-mock.js
- package.json
- Logger mock removing the retrieval of company and display ids to follow recent updates to Logger module in widget-common
> Changes to logger mock regarding ids

- bower.json
- mocks/rss-makeRequest-mock.js
- package.json
@donnapep @stulees please review. cheers
> Added author to the make request mock

- bower.json
- package.json
@stulees @rodrigopavezi please review, @ezequielc FYI. Thanks.
> Update gulp-protractor version

- bower.json
- package.json
- protractor.conf.js
@ezequielc please review. Thanks!
> Configure download folder and disable prompt

- bower.json
- mocks/logger-mock.js
- package.json
- Updating logger-mock to support the version parameter being set
- version bump
> Supporting version parameter in Logger mock

- bower.json
- index.js
- package.json
@donnapep @stulees please review. cheers
> Added test runner for react js

- bower.json
- package.json
@stulees @tejohnso please review. cheers
> Upgraded gulp-protractor due to chrome-drive issue

- bower.json
- package.json
- protractor.conf.js
> Use directConnect to resolve terminated early issue

- bower.json
- mocks/sessionStorage-mock.js
- package.json
@stulees @tejohnso please review. cheers
> Added a mock for sessionStorage

- index.js
@alex-deaconu @rodrigopavezi please review.
> Twitter settings e2e params

- index.js
- package.json
https://circleci.com/gh/Rise-Vision/rise-vision-apps/33590
@ezequielc please review. Thanks!
> Catch coveralls errors and log instead of fail build

- index.js
- package.json
@alex-deaconu Please review. Thanks
> Add the ability to support a 3rd login

- .github/pull_request_template.md
- mocks/translate-mock.js
- package-lock.json
Adds alternative name `mockTranslate` to existing `mockTranlate`. Also adds the commit template used in other repositories.
@alex-deaconu please review
> Add mockTranslate alias to mockTranlate

- package.json
- protractor.conf.js
Remove disable web security flag
This is causing issues with setting cookies
Revert https://github.com/Rise-Vision/widget-tester/pull/118
Apps PR here: https://github.com/Rise-Vision/rise-vision-apps/pull/1466
Validated that this change does not break e2e tests.
No
> Remove disable web security flag

- index.js
- package-lock.json
- package.json
Fix ini vulnerability; update gulp-coveralls
Old plugin no longer maintained
Fix vulnerabilities.
Apps build passes. Coveralls report is generated.
https://github.com/Rise-Vision/rise-vision-apps/pull/2349
No
> Fix ini vulnerability; update gulp-coveralls

- package-lock.json
- package.json
Update mocha to a more recent version
Resolve mocha vulnerabilities.
Apps build passes.
No
> Update mocha to a more recent version

- package-lock.json
- package.json
Update karma to 5 to fix socket.io vulnerability
Fix security vulnerability
Apps build passes.
No
> Update karma to 5 to fix socket.io vulnerability

- package-lock.json
- package.json
Attempt to fix `lodash.template` vulnerability by forcing fixed version as dependency
Vulnerability fix
Will be tested after merging and confirming the vulnerability alert is gone. If not, PR will be reverted.
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why
> Attempt to fix lodash.template vulnerability

- package-lock.json
- package.json
Update karma to resolve vulnerability
Resolve vulnerability.
https://github.com/Rise-Vision/rise-vision-apps/pull/2584
No
> Update karma to resolve vulnerability

- package-lock.json
- package.json
Bump version; out of date with github versions
Fix version
N/A
No
> Bump version; out of date with github versions

- package-lock.json
- package.json
Use npm audit fix for vulnerabilities
Fix vulnerabilities
N/A
No
> Use npm audit fix for vulnerabilities

- index.js
- package-lock.json
- package.json
Remove casperjs to resolve vulnerability
Project is no longer maintained and will
not be receiving updates/fixes
Resolve vulnerabilities
Ran Apps build with this new version
No
> Remove casperjs to resolve vulnerability

- .github/issue_template.md
Add issue template to repo
Development standards
Will validate once merged.
No
> Add issue template to repo
